### ISSUE TITLE
Logstash 5.0 support

### ISSUE THREAD

**Issue by KIVagant** [logstash-plugins/logstash-output-slack#5]
```
/usr/share/logstash/bin/logstash-plugin install logstash-output-slack

...
Bundler could not find compatible versions for gem "logstash-core":
  In snapshot (Gemfile.lock):
    logstash-core (= 5.0.0)

  In Gemfile:
    logstash-core-plugin-api (>= 0) java depends on
      logstash-core (= 5.0.0) java

    logstash-output-slack (>= 0) java depends on
      logstash-core (< 2.0.0, >= 1.4.0) java

    logstash-core (>= 0) java
```

**Comment by reubenpuketapu** [comment]
I also have this issue D:

**Comment by bradymborg** [comment]
me too

**Comment by Solty** [comment]
i have this issue as well.

**Comment by Solty** [comment]
I'm running into the same problem.

**Comment by suyograo** [comment]
PR to add 5.0 support has been merged https://github.com/logstash-plugins/logstash-output-slack/pull/3

@cyli I work on the Logstash team and we'd like to publish an updated version of this plugin. Could you please add `dev_ops@elastic.co` as one of the owners for this gem on RubyGems? `gem owner logstash-output-slack --add dev_ops@elastic.co`

**Comment by cyli** [comment]
@suyograo Yes, done - and I'll make a PR to merge any outstanding changes from https://github.com/cyli/logstash-output-slack in as well (and hopefully deprecate that repo), as I definitely haven't been able to keep up with it.  :)  Thanks

**Comment by suyograo** [comment]
@cyli thank you!

**Comment by suyograo** [comment]
v2.0.1 has been published which supports 5.x
