### ISSUE TITLE
Attachment fields do not have replaced event variables

### ISSUE THREAD

**Issue by mtkage** [logstash-plugins/logstash-output-slack#8]
I am trying to send messages to slack. The issue us that I am not getting replaced values when dealing with attachments. The variable replacement for %{[fields][app]} does not happen in the attachment title. It is working perfectly fine in format though.

- Version: 2.0.1
- Logstash version : 5.3.0
- Operating System: Ubuntu
- Config File:
slack {
        url => <url>
        channel => "%{error_alerts_slack_channel}"
        attachments => [{
          "fallback" => "*Error in %{[fields][app]}*\nEnv - %{[fields][env]}\nRequest - %{requestid}\nServer Time - %{@timestamp}\n\n%{message}"
          "color" => "danger"
          "title" => "Error in %{[fields][app]}"
          "text" => "%{message}"
          "fields" => [{
            "title" => "Application"
            "value" => "%{[fields][app]}"
            "short" => true
          }, {
            "title" => "Env"
            "value" => "%{[fields][env]}"
            "short" => true
          }, {
            "title" => "Request"
            "value" => "%{requestid}"
            "short" => true
          }, {
            "title" => "Server Time"
            "value" => "%{@timestamp}"
            "short" => true
          }]
        }]
      }

**Comment by mtkage** [comment]
And it is not just [field][env]. The problem is happening with all the event variables I am trying to access. I guess it has something to do with the JSON parsing of the attachments that you are doing in line#69 in slack.rb

I am not a ruby expert but that is my hunch.

**Comment by bdwyertech** [comment]
@mtkage see https://github.com/logstash-plugins/logstash-output-slack/pull/7

I built the gemfile and made it available at https://github.com/bdwyertech/logstash-output-slack/releases/tag/interpolation

Seems to work well for me.  I hope my PR gets merged soon, or something similar and improved is implemented.

**Comment by suyograo** [comment]
Fixed in #7
